version: '3.8'

services:
  front-end:
    container_name: env-development
    build:
      context: ../../
      dockerfile: .setup/development/Dockerfile
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next